module.exports = class BookStore_Key {
    formUsername = 'input[id="user-name"]'
    formPassword = 'input[id="password"]'
    buttonLogin  = 'input[id="login-button"]'
    addingToCart = 'button[id="add-to-cart-sauce-labs-onesie"]'
    listProducts = 'div[id="inventory_container"]'
    iconCart = 'a[data-test="shopping-cart-link"]'
    titleOnCartPage = 'span[data-test="title"]'
    iconCheckout = 'button[id="checkout"]'
    titleOnCheckoutPage = 'span[data-test="title"]'
    formFirstName = 'input[id="first-name"]'
    formLastName = 'input[id="last-name"]'
    formPostalcode = 'input[id="postal-code"]'
    buttonContinue = '//*[@id="continue"]'
    titleOnOverview = 'span[data-test="title"]'
    iconFinish = 'button[id="finish"]'
    titleThankyouPage = 'h2[data-test="complete-header"]'
    iconBackHome = 'button[id="back-to-products"]'
}
